name: Fetch Latest News

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch: {}
  push:
    paths:
      - ".github/workflows/fetch-news.yml"
      - "scripts/**"
      - "package.json"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm install

      - name: Build latest.json
        env:
          FEEDS: ${{ secrets.FEEDS }}
        run: node scripts/fetch-news.mjs

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/data/latest.json
          git commit -m "chore: update latest news [skip ci]" || echo "No changes"
          git push
